### ISSUE TITLE
Panic when drawing >222

### ISSUE THREAD

**Issue by GeTechG** [nokola/nonaquad#2] opened 2021-07-26 04:32 UTC
A panic is thrown out if >222 iterations.
```rust
for i in 0..223 {
            nona.begin_path();
            nona.circle(Point::new(i as f32, 0.), 32.);
            nona.fill_paint(Paint::from(nona::Color::rgb_i(255, 0,0)));
            nona.fill().unwrap();
}
```

```rust
thread 'main' panicked at 'assertion failed: size <= self.size', /home/sergey/.cargo/registry/src/github.com-1ecc6299db9ec823/miniquad-0.3.0-alpha.37/src/graphics.rs:1715:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:50:5
   3: miniquad::graphics::Buffer::update
             at /home/sergey/.cargo/registry/src/github.com-1ecc6299db9ec823/miniquad-0.3.0-alpha.37/src/graphics.rs:1715:9
   4: <nvg_miniquad::nvgimpl::Renderer as nona::renderer::Renderer>::flush
             at ./nonaquad/src/nvgimpl.rs:720:9
   5: nona::context::Context<R>::end_frame
             at ./nona/src/context.rs:522:9
   6: macroquad_vector_render::amain::{{closure}}
             at ./src/main.rs:111:9
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/sergey/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
   8: macroquad::exec::resume
             at /home/sergey/.cargo/registry/src/github.com-1ecc6299db9ec823/macroquad-0.3.7/src/exec.rs:65:17
   9: <macroquad::Stage as miniquad::event::EventHandlerFree>::draw::{{closure}}
             at /home/sergey/.cargo/registry/src/github.com-1ecc6299db9ec823/macroquad-0.3.7/src/lib.rs:584:24
  10: <macroquad::Stage as miniquad::event::EventHandlerFree>::draw::maybe_unwind
             at /home/sergey/.cargo/registry/src/github.com-1ecc6299db9ec823/macroquad-0.3.7/src/lib.rs:575:21
  11: <macroquad::Stage as miniquad::event::EventHandlerFree>::draw
             at /home/sergey/.cargo/registry/src/github.com-1ecc6299db9ec823/macroquad-0.3.7/src/lib.rs:580:26
  12: miniquad::frame
             at /home/sergey/.cargo/registry/src/github.com-1ecc6299db9ec823/miniquad-0.3.0-alpha.37/src/lib.rs:272:5
  13: sapp_linux::_sapp_call_frame
             at /home/sergey/.cargo/registry/src/github.com-1ecc6299db9ec823/sapp-linux-0.1.13/src/lib.rs:2627:13
  14: sapp_linux::_sapp_frame
             at /home/sergey/.cargo/registry/src/github.com-1ecc6299db9ec823/sapp-linux-0.1.13/src/lib.rs:2639:5
  15: sapp_run
             at /home/sergey/.cargo/registry/src/github.com-1ecc6299db9ec823/sapp-linux-0.1.13/src/lib.rs:2783:9
  16: miniquad::start
             at /home/sergey/.cargo/registry/src/github.com-1ecc6299db9ec823/miniquad-0.3.0-alpha.37/src/lib.rs:433:14
  17: macroquad::Window::from_config
             at /home/sergey/.cargo/registry/src/github.com-1ecc6299db9ec823/macroquad-0.3.7/src/lib.rs:652:9
  18: macroquad::Window::new
             at /home/sergey/.cargo/registry/src/github.com-1ecc6299db9ec823/macroquad-0.3.7/src/lib.rs:641:9
  19: macroquad_vector_render::main
             at ./src/main.rs:51:1
  20: core::ops::function::FnOnce::call_once
             at /home/sergey/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by nokola** [comment] 2021-07-26 07:44
Fixed! 
Issue was that vertex count was exceeding GPU buffer max vertices on some platforms (WebGL, OpenGL ES 2 on Android.)
I fixed it by adding GPU flush() in case draw count increases past the limit.
May improve further in the future if needed.

Note that nona.begin_frame(...) now takes optional color to clear screen. 
I updated example here: https://github.com/nokola/nonaquad/blob/master/examples/drawaa.rs#L39

```rust
nona.begin_frame(Some(Color::rgb_i(128, 128, 255))).unwrap();
```

I tested drawing 405 circles and looks good! :)
```rust
        for i in 0..405 {
            nona.begin_path();
            // nona.rect((100.0, 100.0, 400.0, 300.0));
            nona.circle(Point::new(i as f32, 110.), 32.);
            nona.fill_paint(Paint::from(Color::rgb_i(255, (i as u32 % 256 as u32) as u8, 0)));
            nona.fill().unwrap();
        }

```
![image](https://user-images.githubusercontent.com/6869225/126951544-65bd0429-7ab9-48ee-a8ae-b99299f4cf9f.png)

**Comment by GeTechG** [comment] 2021-07-26 08:02
Okay, thank you!

**Comment by nokola** [comment] 2021-07-26 08:50
Good suggestion! I made the sources a bit simpler - moved nona to nonaquad repo, and made sure example is working.
Now everything is in one repository using Rust workspaces, and dependencies resolve.

**Comment by nokola** [comment] 2021-07-26 09:16
Published nona and nonaquad on crates.io!

**Comment by nokola** [comment] 2021-07-26 09:22
btw, if the issue is fixed for you, please close it! Thanks!

**Comment by nokola** [comment] 2021-08-17 20:49
Fixed

**Closed by nokola** 2021-08-17 20:49 UTC
